server:
  address: 127.0.0.1
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
spring:
  threads.virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost/learning
    username: postgres
    password: "@z9X}r6hF£>8J2r_"
logging.level.org.zalando.logbook.Logbook: DEBUG
authentication.mocked: true
authentication.mocked-id: 74d88fa1-cc2d-4bdb-bf64-a7335b1cdd04
