server:
  address: 127.0.0.1
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
spring:
  threads.virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost/learning
    username: postgres
    password: "@z9X}r6hF£>8J2r_"
logging.level.org.zalando.logbook.Logbook: DEBUG
authentication.mocked: false
authentication.mocked-id: 74d88fa1-cc2d-4bdb-bf64-a7335b1cdd04
login-redirect-success-uri: https://localhost/home
login-redirect-fail-uri: https://localhost/sign-in
google-client-id: 2547423840-ahppq370e0gdvvn0hb0blmk2o3hrvj9i.apps.googleusercontent.com
jwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 86400
---

spring:
  config:
    activate:
      on-profile: production
login-redirect-success-uri: https://softhlon-learning.tech/home
login-redirect-fail-uri: https://softhlon-learning.tech/sign-in
google-client-id: 2547423840-rdu8roke4tgser7dl4qo1bh628rdamp6.apps.googleusercontent.com
