server:
  address: localhost
spring:
  threads.virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost/learning
    username: postgres
    password: "@z9X}r6hF£>8J2r_"
    hikari.maximum-pool-size: 16
  mail.host: java-fullstack.tech
  mail.port: 25
  mail.properties.mail.smtp.starttls.enable: true
  output.ansi.enabled: ALWAYS
send-emails.enabled: false
logging.level.org.zalando.logbook.Logbook: DEBUG
authentication.mocked: false
authentication.mocked-id: 74d88fa1-cc2d-4bdb-bf64-a7335b1cdd04
login-redirect-success-uri: https://localhost/home
login-redirect-fail-uri: https://localhost/sign-in
google-client-id: 2547423840-ahppq370e0gdvvn0hb0blmk2o3hrvj9i.apps.googleusercontent.com
jwt:
  secret: 75a839dab1e167e6e1a6dc273247dec588cabe62f96142704a802d673ac94ab7
  expiration: 86400
update-password.base-url: "https://localhost/update-password?token="
activate-account.base-url: "https://localhost/activate-account?token="
logging.pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} | %clr(%-5level){green} | %X{account} | %msg%n"
service.base-url: "https://localhost"
stripe.api-key: "sk_test_51QmNzsIdZlPlV5wEyJEDGjierQfxyKkJVsuhjbvMMtxnjex89QWnOiRIkV8nwccigHjmX6Fqh0VCTSFnO0TwZJW500de6la5pX"
stripe.checkout-completed.webhook.secret: "whsec_Nyb8rWd6bwKHWMspS0AMwBuJRizTzBDN"
stripe.customer-created.webhook.secret: "whsec_gbBnvFEzJ6qgTxhttTARp1hkmtntE87B"
stripe.subscription-created.webhook.secret: "whsec_X9MWm4LodiEznxPCgxv09mIV2hoeSYaj"
stripe.subscription-updated.webhook.secret: "whsec_dzQA5hLseKTXdKzJbHhvNYcuPyugauDd"
stripe.invoice-paid.webhook.secret: "whsec_ovQ07fYwLsKlhHtRXAjqSRHUOGwJeiUr"
stripe.subscription-deleted.webhook.secret: "whsec_9cactNFNgHm0uXk2XUG2qBKV5kWvfpfQ"
stripe.generic-event.webhook.secret: "whsec_dC3HqyfYzsAbXlaF64tkZjtV4nTDtXWV"

---
spring:
  config:
    activate:
      on-profile: production
send-emails.enabled: true
login-redirect-success-uri: https://java-fullstack.tech/home
login-redirect-fail-uri: https://java-fullstack.tech/sign-in
google-client-id: 261285487242-kd1e2lhqdpfrph48o00ga0h21qrebh41.apps.googleusercontent.com
update-password.base-url: "https://java-fullstack.tech/update-password?token="
activate-account.base-url: "https://java-fullstack.tech/activate-account?token="
service.base-url: "https://java-fullstack.tech"
