#!/bin/sh

# PROVIDE: backend 
# REQUIRE: DAEMON mountlate
# KEYWORD: shutdown 
. /etc/rc.subr
 
name=backend
rcvar=backend_enable
backend_user=learning
backend_chdir="/home/admin/learning-platform/backend"
 
pidfile="/var/run/backend/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -o /var/log/backend.log -p ${pidfile} /usr/local/bin/java -Xms4g -Xmx4g -jar /home/admin/learning-platform/backend/application/backend.jar --spring.profiles.active=production"

stop_cmd="stop"
status_cmd="status"
restart_cmd="restart"

stop () {
        if [ -e ${pidfile} ]; then
                echo Stopping ${name}
		kill `cat ${pidfile}`
		killall java
        else
                echo ${name} is not running.
        fi
}

status () {
        if [ -e ${pidfile} ]; then
                echo ${name} is running.
        else
                echo ${name} is not running.
        fi
}

restart () {
 	stop
	sleep 1
 	run_rc_command start
}

load_rc_config $name
run_rc_command "$1"
