#!/usr/local/bin/bash

sudo service frontend stop
sudo service backend stop
sudo rm -fr /home/admin/learning-platform
gh repo clone softhlon-learning/learning-platform
cd /home/admin/learning-platform/backend
mvn clean install&
cd /home/admin/learning-platform/frontend
yarn install
sudo chown -R learning /home/admin/learning-platform/frontend
sudo service backend start
sudo service frontend start
