#!/usr/local/bin/bash

echo Upgrade started.

sudo service frontend stop
sudo service backend stop
sudo rm -fr /home/admin/learning-platform
cd
gh repo clone softhlon-learning/learning-platform
cd /home/admin/learning-platform/backend
mvn clean install
cp application/target/backend.jar application/backend.jar
mvn clean
sudo service backend start
cd /home/admin/learning-platform/frontend
yarn install
sudo chown -R learning /home/admin/learning-platform/frontend
sudo service frontend start

echo Upgrade finished.
