services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: learning-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
