services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: learning-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@z9X}r6hF£>8J2r_
    ports:
      - '127.0.0.1:5432:5432'
